name: Build and push image
on:
  push:
    tags:
      - '*'
      - '!flux-sync'
jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install jsonnet
        run: ./scripts/install_jsonnet.sh

      - name: get google creds
        shell: bash
        env:
          GKEY: ${{secrets.GOOGLE_KEY}}
        run: |
          'echo "$GKEY" > gsecrets.json'
          cat keyfile.json | docker login -u _json_key --password-stdin https://[HOSTNAME]


      - name: build
        run: make docker

      - name: push
        env: 
          GKEY: ${{secrets.GOOGLE_KEY}}

        run: |
          # fixme - get the hostname from the registry name
          'echo "$GKEY"' | docker login -u _json_key --password-stdin https://eu.gcr.io
          make push
