on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        
      - name: install jsonnet
        run: ./deploy/scripts/install_jsonnet.sh

      - name: get url
        id: url
        working-directory: ./deploy
        run: echo ::set-output name=url::$(jsonnet -e '(import "config.jsonnet").k8s.root_dns_name')

      - name: check main webapp
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://${{ steps.url.outputs.url }}

      - name: check staging webapp
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://staging-${{ steps.url.outputs.url }}
