on:
  push:
    branches:
      - master

jobs:
  apply:
    runs-on: ubuntu-18.04
    container: bitnami/jsonnet
    steps:
      - uses: actions/checkout@v2

      - name: Install terraform
        uses: little-core-labs/install-terraform@v1

          
      - name: run terraform apply
        run: |
          echo ${{secrets.GOOGLE_KEY}} > deploy/terraform/main/tfsecrets.json
          cd deploy
          make tfapply
