on:
  push:
    branches:
      - master

jobs:
  apply:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install terraform
        uses: little-core-labs/install-terraform@v1

      - name: Install jsonnet
        run: ./deploy/scripts/install_jsonnet.sh

      - name: install kubeseal
        run: ./deploy/scripts/install_kubeseal.sh
          
      - name: install creds file
        working-directory: ./deploy
        shell: bash
        env:
          GKEY: ${{secrets.GOOGLE_KEY}}
        run: 'echo "$GKEY" > ./terraform/main/tfsecrets.json'

      - name: run tf init
        working-directory: ./deploy
        run: make tfinit

      - name: run terraform apply
        working-directory: ./deploy
        run: make tfapply

      - name: reseal
        # if the secrets have changed, then we'll need to make new sealed
        # versions
        working-directory: ./deploy/k8s
        run: make seal

        # nb - no need to regenerate the k8s manifests, flux does that in cluster.
        
        # commit any changes back to the repo
      - uses: stefanzweifel/git-auto-commit-action@v4.1.4
        with:
          commit_message: 'ci-commit: update changes dependent on tf run'
