on:
  push:
    branches:
      - master

jobs:
  apply:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install terraform
        uses: little-core-labs/install-terraform@v1

      - name: Install jsonnet
        run: |
          wget https://github.com/google/jsonnet/releases/download/v0.15.0/jsonnet-bin-v0.15.0-linux.tar.gz
          tar xzf jsonnet-bin-v0.15.0-linux.tar.gz
          rm jsonnet-bin-v0.15.0-linux.tar.gz
          chmod a+x jsonnet
          sudo install jsonnet /usr/local/bin/jsonnet

        
          
      - name: run terraform apply
        run: |
          echo ${{secrets.GOOGLE_KEY}} > deploy/terraform/main/tfsecrets.json
          cd deploy
          make tfapply
